package alfredproject;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ben
 */
import java.io.*;
public class OptionsGUI extends javax.swing.JFrame {

    /**
     * Creates new form OptionsGUI
     */
    public Alfredproject ap = new Alfredproject();
    public OptionsGUI() {
        //start of Options window
        initComponents();
        //sets text boxes to set variables
        txtBotName.setText(ap.BotName);
        txtThankYouResponse.setText(ap.ThankYouResponse);
        txtFinishingStatement.setText(ap.FinishingStatement);
        txtZipCode.setText(ap.ZipCode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTheAlfredProjectOptions = new javax.swing.JLabel();
        lblBotName = new javax.swing.JLabel();
        txtThankYouResponse = new javax.swing.JTextField();
        txtBotName = new javax.swing.JTextField();
        txtVoice = new javax.swing.JTextField();
        lblVoice = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        lblThankYouResponse = new javax.swing.JLabel();
        lblVoice1 = new javax.swing.JLabel();
        txtFinishingStatement = new javax.swing.JTextField();
        lblzipcode = new java.awt.Label();
        txtZipCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTheAlfredProjectOptions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTheAlfredProjectOptions.setText("The Alfred Project Options");

        lblBotName.setText("Bot Name");

        txtThankYouResponse.setText("You're welcome, sir.");

        txtBotName.setText("Alfred");

        txtVoice.setText("Kevin16");

        lblVoice.setText("Voice: Coming Soon");

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        lblThankYouResponse.setText("Thank You Response");

        lblVoice1.setText("Finishing Statement");

        txtFinishingStatement.setText("It is done, sir");

        lblzipcode.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblzipcode.setText("Zip Code or Weather Code");

        txtZipCode.setText("55446");
        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblTheAlfredProjectOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblVoice)
                                    .addComponent(lblThankYouResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBotName)
                                    .addComponent(lblVoice1)
                                    .addComponent(lblzipcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBotName)
                                    .addComponent(txtVoice)
                                    .addComponent(txtThankYouResponse)
                                    .addComponent(txtFinishingStatement)
                                    .addComponent(txtZipCode))))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTheAlfredProjectOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBotName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBotName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThankYouResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThankYouResponse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoice1)
                    .addComponent(txtFinishingStatement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblzipcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnOK)
                    .addComponent(btnReset)
                    .addComponent(btnApply))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //back is pressed
        super.hide();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed

        //sets bot name
        ap.BotName = txtBotName.getText().toLowerCase();
        //sets bot response
        ap.ThankYouResponse = txtThankYouResponse.getText().toLowerCase();
        //sets finishing statement
        ap.FinishingStatement = txtFinishingStatement.getText().toLowerCase();
        //sets up zipcode
        ap.ZipCode=txtZipCode.getText().toLowerCase();
        try{
        SaveIO save = new SaveIO();
        save.Save();
        
        //closes options window
        } catch(IOException e){
           
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplyActionPerformed
   
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        //Ok buttons is pressed

        //sets bot name
        ap.BotName = txtBotName.getText().toLowerCase();
        //sets bot response
        ap.ThankYouResponse = txtThankYouResponse.getText().toLowerCase();
        //sets finishing statement
        ap.FinishingStatement = txtFinishingStatement.getText().toLowerCase();
        //sets zipcode
        ap.ZipCode=txtZipCode.getText().toLowerCase();
        try{
        SaveIO save = new SaveIO();
        save.Save();
        
        //closes options window
        super.hide();
        } catch(IOException e){
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtBotName.setText("Alfred");
        txtThankYouResponse.setText("You're welcome.");
        txtVoice.setText("Kevin16");
        txtFinishingStatement.setText("It is done, sir.");
        txtZipCode.setText("55447");
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblBotName;
    private javax.swing.JLabel lblThankYouResponse;
    private javax.swing.JLabel lblTheAlfredProjectOptions;
    private javax.swing.JLabel lblVoice;
    private javax.swing.JLabel lblVoice1;
    private java.awt.Label lblzipcode;
    private javax.swing.JTextField txtBotName;
    private javax.swing.JTextField txtFinishingStatement;
    private javax.swing.JTextField txtThankYouResponse;
    private javax.swing.JTextField txtVoice;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
